### PR TITLE
Schema builder fixes

### LINKED ISSUE #390: Schema builder: icon picker broken for groups
The UI doesn't set the icon properly for groups, works fine for params.

### PR DESCRIPTION
**Pull request by ewels**
Updates to the JSON schema builder to fix bugs discovered by @MaxUlysse:

* Icon picker was broken for dynamically added groups and params
* Modals were too parameter specific in places, now customised for params / groups.

I also added the icon to the help text preview.

Closes #390 and #391

### CODE REVIEW

File: public_html/assets/js/nf-core-schema-builder.js [hunk 1]
```diff
@@ -539,8 +539,20 @@ $(function () {
...
-        $('.helptext-preview-title').text('--'+id);
+        var modal_header = 'params.<span>'+id+'</span>';
+        var preview_cli_title = '--'+id;
+        var preview_web_title = '<code>--'+id+'</code>';
+        if(param['type'] == 'object'){
+            modal_header = '<span>'+id+'</span>';
+            preview_cli_title = '== '+id+' ==';
+            preview_web_title = id;
+        }
+        if(param['fa_icon'] !== undefined && param['fa_icon'].length > 3){
```
Comment (mashehu) [inline public_html/assets/js/nf-core-schema-builder.js:550]: Just out of curiosity, why  `param['fa_icon'].length > 3`, is it to check if it is more than `far/fab/fas`?

Comment (ewels) [reply public_html/assets/js/nf-core-schema-builder.js:550]: Microsecond random decision as I was typing, so not a lot of thought went into it. But yes, basically.

File: public_html/json_schema_build.php [hunk 2]
```diff
@@ -369,24 +369,24 @@ function validate_cache_id($cache_id){
...
                         <div class="card-body tab-content">
                             <div class="tab-pane fade show active" id="tab-helptext" role="tabpanel">
-                                <div class="form-group help_text_modal_group">
+                                <div class="form-group help_text_modal_group mb-0">
                                     <textarea class="form-control" id="help_text_input" rows="5"></textarea>
-                                    <small class="form-text text-muted">
-                                        You can use <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">markdown</a>,
-                                        but remember that this will be shown raw on the command line. So no tables please!
+                                    <small class="form-text text-muted mt-2">
+                                        <i class="fab fa-markdown"></i> <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> supported,
```
Comment (mashehu) [inline public_html/json_schema_build.php:375]:
```suggestion
                                        <i class="fab fa-markdown"></i> <a href="https://www.markdownguide.org/cheat-sheet/" target="_blank">Markdown</a> is supported,
```
