### PR TITLE
Fix header id generation

### LINKED ISSUE #175: Not all links in MD are available the website
I have that in the docs: https://github.com/nf-core/sarek/blob/dev/docs/usage.md#--skipqc
But that won't work in the website: https://nf-co.re/sarek//docs/usage#--skipQC

### PR DESCRIPTION
**Pull request by mashehu**
fixes #175

### CODE REVIEW

File: includes/header.php [hunk 1]
```diff
@@ -77,10 +77,11 @@
   // Add ID attributes to headers
   $hids = Array();
   $content = preg_replace_callback(
-    '~<h([1234])>([^<]*)</h([1234])>~Ui', // Ungreedy by default, case insensitive
+    '~<h([1234])>(\S*)</h([1234])>~Ui', // Ungreedy by default, case insensitive
```
Comment (ewels) [inline includes/header.php]: Does this work with headers that have whitespace? eg. `<h1>This Header</h1>`?

More generally, why the change?

File: public_html/assets/css/nf-core-dark.css [hunk 2]
```diff
@@ -56,6 +56,13 @@ blockquote {
   background-color: #181A1B;
   border-color: rgba(102, 102, 102, 0.13);
 }
+/* .stats_keynumbers .bg-icon {
```
Comment (ewels) [inline public_html/assets/css/nf-core-dark.css]: Please remove this again if it's not needed..

File: includes/header.php (hunk 1 above)
Comment (mashehu) [reply includes/header.php]: I had to change it, because ```[^<]*``` didn't catch ```<code>match</code>``` pieces.
Hmm, yes, this actually breaks headers with a whitespace, sorry. 
How about ```~<h([1234])>(.*?)</h([1234])>~Ui``` or is that to general?

File: public_html/assets/css/nf-core-dark.css (hunk 2 above)
Comment (mashehu) [reply public_html/assets/css/nf-core-dark.css]: Sorry, this was an artifact while creating the before-after screenshots, see commit 
0f06535.

File: includes/header.php (hunk 1 above)
Comment (ewels) [reply includes/header.php]: Yes I was going to say that it should work, as long as we have the ungreedy `U` modifier so that it doesn't match the whole file...

Comment (mashehu) [reply includes/header.php]: I made it more general now (see 164ceee). 
While testing, I found two different problems with the links from the ToC of the Usage section of bcellmagic (https://nf-co.re/bcellmagic/docs/usage). 
- The `-profile`'s href is to `#-profile-single-dash` 
= The `<li>`s underneath shouldn't appear there, since they are no `<h>` elements. Not sure if that is coming from the repo or the backend, so I don't know where to open the respective issue or fix the problem.

Comment (ewels) [reply includes/header.php]: `-profile` should be one hyphen (it’s a core Nextflow option, not a pipeline param) and the markdown (including ToC) comes from the pipeline. So needs to be fixed there if anywhere I guess..
