### PR TITLE
don't add highlight markers inside html tags.

### LINKED ISSUE #1066: Broken link in Pipeline configuration
The documentation [here](https://nf-co.re/usage/configuration?q=google) has a broken link in the first paragraph in the introduction.  I get this link when viewing the page: [Google Cloud](https://cloud.%3Cmark%3Egoogle%3C/mark%3E.com/).  The underlying link is `https://cloud.%3Cmark%3Egoogle%3C/mark%3E.com/`.  But the markdown looks fine: https://github.com/nf-core/nf-co.re/blob/c6b04680ad8d6dfd6a3981d90f9dc51543b9acb4/markdown/usage/configuration.md?plain=1#L8, so I am not sure how to fix this.

### PR DESCRIPTION
**Pull request by mashehu**
Not sure if there is a more elegant regex to exclude html parameters from regex matches. What do you think, @ewels 

Fixes #1066 

<a href="https://gitpod.io/#https://github.com/nf-core/nf-co.re/pull/1152"></a>

### CODE REVIEW

File: includes/parse_md.php [hunk 1]
```diff
@@ -74,9 +74,13 @@ function parse_md($markdown) {
     $pd = new ParsedownExtra();
     $content = $pd->text($md);
 
-    // Highlight any search terms if we have them
+    // Highlight any search terms if we have them (except if they are inside html tags)
     if (isset($_GET['q']) && strlen($_GET['q'])) {
-        $content = preg_replace('/(' . $_GET['q'] . ')/i', "<mark>$1</mark>", $content);
+        $content = preg_replace(
+            '/<.*?' . $_GET['q'] . '.*?>(*SKIP)(*FAIL)|' . $_GET['q'] . '/i',
```
Comment (ewels) [inline includes/parse_md.php:80]: WHAT BLACK MAGIC IS THIS?!

Comment (mashehu) [reply includes/parse_md.php:80]: Found it on SO and I find it more read able then the lookahead a la ` (?=.*?<.*?/>)`

Comment (ewels) [reply includes/parse_md.php:80]: If it works, then great! I've never seen it before.

**Review by ewels — APPROVED** [review]
