### PR TITLE
Fix pipeline health page, add template branch protection

### LINKED ISSUE #638: Add branch protection to TEMPLATE
I think it would be a good idea to limit the `TEMPLATE` branch for each pipeline to `nf-core-bot`

I actually implemented that in nf-core/sarek, but that's one pipeline, we can and should automatize that for all pipelines.

### PR DESCRIPTION
**Pull request by ewels**
* Refactor code to check HTTP API response codes
    * GitHub changed the exact string that they return in the HTTP header for successful responses (`HTTP/1.1 200` instead of `HTTP/1.1 200 OK`) which broke everything.
    * Refactored the code that checks these strings to work with the new + old format.
* Added new test for branch protection on `TEMPLATE`
  * Simpler than branch protection for `dev` and `master` - just checks that nothing is allowed apart from pushes from @nf-core-bot

Closes #638

### CODE REVIEW

File: public_html/pipeline_health.php [hunk 1]
```diff
@@ -687,6 +734,7 @@ function get_gh_team_repos($team){
   'branch_dev_code_owner_reviews' => 'dev: code owner reviews',
   'branch_dev_required_num_reviews' => 'dev: 1 review',
   'branch_dev_enforce_admins' => 'dev: enforce admins',
+  'branch_template_restrict_push' => 'T push',
```
Comment (mashehu) [inline public_html/pipeline_health.php:737]:
```suggestion
  'branch_template_restrict_push' => 'TEMPLATE: restrict push',
```
Any reason to keep it so short?

**Review by mashehu — APPROVED** [review]

File: public_html/pipeline_health.php (hunk 1 above)
Comment (ewels) [reply public_html/pipeline_health.php:737]: Yeah, I wrote that originally but it makes the column a lot wider, compressing all of the other columns a lot as a result.

The header isn't so important any more to be honest as we have so many repos that it usually scrolls out of view quite quickly. Hovering over any cells in the column shows the full description so it's easy to see what the failures are.
